### ISSUE TITLE
sudo npm install -g oval fails with permission problem

### ISSUE THREAD

**Issue by DavidBiesack** [whitlockjc/oval#1] opened 2018-08-13 13:08 UTC
On Mac OS X:
```bash
$ npm --version
5.6.0
$ node --version
v8.11.3
$ sudo npm install -g oval
/usr/local/bin/oval -> /usr/local/lib/node_modules/oval/bin/oval

> jsonpath@1.0.0 postinstall /usr/local/lib/node_modules/oval/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

sh: generated/aesprim-browser.js: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jsonpath@1.0.0 postinstall: `node lib/aesprim.js > generated/aesprim-browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jsonpath@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/david.biesack/.npm/_logs/2018-08-13T12_55_48_885Z-debug.log
```

Similar issues arise with other npm packages depending on jsonpath; see https://github.com/dchester/jsonpath/issues/105

```bash
sudo npm install -g oval  --unsafe-perm=true --allow-root 
```
allows oval install to work with `sudo`.

I realize this may not be an issue with oval, but this issue and this workaround may help others who run into the permission problem.

**Comment by whitlockjc** [comment] 2018-08-13 15:15
Yeah, I'm not sure how `oval` is the cause so I'll close it but I do think it's useful for reference.  Thanks!

**Closed by whitlockjc** 2018-08-13 15:15 UTC
